sudo: false
arch:
  - amd64
  - ppc64le
language: node_js

node_js:
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'

matrix:
  fast_finish: true

script:
  if [ $(echo "${TRAVIS_NODE_VERSION}" | cut -d'.' -f1) -ge 4 ]; then
    npm run coveralls;
  else
    npm test;
  fi
